import { canonicalJson, sha256Hex } from './hashBenchmarkPack';
import { calculateScoreBreakdown } from './scoring';
import type {
  BenchmarkPack,
  BenchmarkResult,
  ModelProviderConfig,
  ResultManifestSignature,
  SignedResultManifest,
} from '../types/benchmark';

export const APP_VERSION = '0.1.0';
const SIGNING_KEY_STORAGE = 'frcbench:signingPrivateKeyJwk';
const SIGNING_ALGORITHM = 'ECDSA-P256-SHA256' as const;

export interface LocalSigningKey {
  privateKey: CryptoKey;
  publicKey: CryptoKey;
  publicKeyJwk: JsonWebKey;
  fingerprint: string;
}

export interface SignedResultVerification {
  valid: boolean;
  reason: string;
  manifest?: SignedResultManifest;
}

export async function generateLocalSigningKey(savePrivateKey: boolean): Promise<LocalSigningKey> {
  const keyPair = await crypto.subtle.generateKey(
    {
      name: 'ECDSA',
      namedCurve: 'P-256',
    },
    true,
    ['sign', 'verify'],
  );

  const publicKeyJwk = await crypto.subtle.exportKey('jwk', keyPair.publicKey);
  const privateKeyJwk = await crypto.subtle.exportKey('jwk', keyPair.privateKey);
  const fingerprint = await fingerprintPublicKey(publicKeyJwk);

  if (savePrivateKey) {
    localStorage.setItem(SIGNING_KEY_STORAGE, JSON.stringify(privateKeyJwk));
  } else {
    localStorage.removeItem(SIGNING_KEY_STORAGE);
  }

  return {
    privateKey: keyPair.privateKey,
    publicKey: keyPair.publicKey,
    publicKeyJwk,
    fingerprint,
  };
}

export async function loadStoredSigningKey(): Promise<LocalSigningKey | null> {
  const raw = localStorage.getItem(SIGNING_KEY_STORAGE);
  if (!raw) {
    return null;
  }

  try {
    const privateKeyJwk = JSON.parse(raw) as JsonWebKey;
    const privateKey = await crypto.subtle.importKey(
      'jwk',
      privateKeyJwk,
      { name: 'ECDSA', namedCurve: 'P-256' },
      true,
      ['sign'],
    );
    const publicKeyJwk = privateJwkToPublicJwk(privateKeyJwk);
    const publicKey = await importPublicKey(publicKeyJwk);
    const fingerprint = await fingerprintPublicKey(publicKeyJwk);

    return {
      privateKey,
      publicKey,
      publicKeyJwk,
      fingerprint,
    };
  } catch {
    localStorage.removeItem(SIGNING_KEY_STORAGE);
    return null;
  }
}

export function forgetStoredSigningKey() {
  localStorage.removeItem(SIGNING_KEY_STORAGE);
}

export async function createUnsignedResultManifest({
  pack,
  packHash,
  results,
  config,
}: {
  pack: BenchmarkPack;
  packHash: string;
  results: BenchmarkResult[];
  config: ModelProviderConfig;
}): Promise<SignedResultManifest> {
  const summary = calculateScoreBreakdown(results);
  const timestamp = new Date().toISOString();

  return {
    schemaVersion: 'frcbench.signed-result.v1',
    appName: 'FRCBench',
    benchmarkPackId: pack.id,
    benchmarkPackVersion: pack.version,
    benchmarkPackHash: packHash,
    runId: crypto.randomUUID(),
    timestamp,
    modelProvider: config.providerName,
    modelName: results[0]?.modelName || config.modelName,
    apiBaseUrl: config.baseUrl,
    temperature: config.temperature,
    maxTokens: config.maxTokens,
    totalScore: summary.totalScore,
    maxScore: summary.totalMaxScore,
    percentScore: summary.percentScore,
    categoryBreakdown: summary.byCategory,
    seasonBreakdown: summary.bySeason,
    difficultyBreakdown: summary.byDifficulty,
    taskResults: results,
    environment: {
      userAgent: navigator.userAgent,
      appVersion: APP_VERSION,
      browserTimestamp: timestamp,
      note: 'Client-side generated by FRCBench. No server-side attestation is implied.',
    },
    signature: null,
  };
}

export async function signResultManifest(
  manifest: SignedResultManifest,
  signingKey: LocalSigningKey,
): Promise<SignedResultManifest> {
  const signedAt = new Date().toISOString();
  const bytes = new TextEncoder().encode(canonicalManifestForSigning(manifest));
  const signature = await crypto.subtle.sign(
    {
      name: 'ECDSA',
      hash: 'SHA-256',
    },
    signingKey.privateKey,
    bytes,
  );

  const signaturePayload: ResultManifestSignature = {
    algorithm: SIGNING_ALGORITHM,
    publicKeyJwk: signingKey.publicKeyJwk,
    publicKeyFingerprint: signingKey.fingerprint,
    signatureValue: arrayBufferToBase64Url(signature),
    signedAt,
  };

  return {
    ...manifest,
    signature: signaturePayload,
  };
}

export async function verifySignedResultManifest(input: unknown): Promise<SignedResultVerification> {
  if (!isManifestLike(input)) {
    return {
      valid: false,
      reason: 'The imported file is not a FRCBench signed result manifest.',
    };
  }

  if (!input.signature) {
    return {
      valid: false,
      reason: 'The manifest does not include a signature.',
      manifest: input,
    };
  }

  if (input.signature.algorithm !== SIGNING_ALGORITHM) {
    return {
      valid: false,
      reason: `Unsupported signature algorithm: ${input.signature.algorithm}.`,
      manifest: input,
    };
  }

  try {
    const publicKey = await importPublicKey(input.signature.publicKeyJwk);
    const signature = base64UrlToArrayBuffer(input.signature.signatureValue);
    const bytes = new TextEncoder().encode(canonicalManifestForSigning(input));
    const valid = await crypto.subtle.verify(
      {
        name: 'ECDSA',
        hash: 'SHA-256',
      },
      publicKey,
      signature,
      bytes,
    );

    return {
      valid,
      reason: valid
        ? 'Signature is valid. The manifest has not changed since it was signed with this public key.'
        : 'Signature is invalid. The manifest may have been changed or signed with a different key.',
      manifest: input,
    };
  } catch (error) {
    return {
      valid: false,
      reason: error instanceof Error ? error.message : 'Could not verify signature.',
      manifest: input,
    };
  }
}

export function canonicalManifestForSigning(manifest: SignedResultManifest): string {
  return canonicalJson({
    ...manifest,
    signature: null,
  });
}

export async function fingerprintPublicKey(publicKeyJwk: JsonWebKey): Promise<string> {
  const hash = await sha256Hex(canonicalJson(normalizePublicKeyJwk(publicKeyJwk)));
  return hash.match(/.{1,4}/g)?.slice(0, 8).join(':') ?? hash.slice(0, 32);
}

function normalizePublicKeyJwk(publicKeyJwk: JsonWebKey) {
  return {
    crv: publicKeyJwk.crv,
    kty: publicKeyJwk.kty,
    x: publicKeyJwk.x,
    y: publicKeyJwk.y,
  };
}

function privateJwkToPublicJwk(privateKeyJwk: JsonWebKey): JsonWebKey {
  const { d: _privateScalar, ...publicKeyJwk } = privateKeyJwk;
  return publicKeyJwk;
}

function importPublicKey(publicKeyJwk: JsonWebKey) {
  return crypto.subtle.importKey(
    'jwk',
    publicKeyJwk,
    { name: 'ECDSA', namedCurve: 'P-256' },
    true,
    ['verify'],
  );
}

function isManifestLike(input: unknown): input is SignedResultManifest {
  return (
    typeof input === 'object' &&
    input !== null &&
    'schemaVersion' in input &&
    input.schemaVersion === 'frcbench.signed-result.v1' &&
    'appName' in input &&
    input.appName === 'FRCBench'
  );
}

function arrayBufferToBase64Url(buffer: ArrayBuffer) {
  const bytes = new Uint8Array(buffer);
  let binary = '';
  bytes.forEach((byte) => {
    binary += String.fromCharCode(byte);
  });
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
}

function base64UrlToArrayBuffer(value: string) {
  const padded = value.replace(/-/g, '+').replace(/_/g, '/').padEnd(Math.ceil(value.length / 4) * 4, '=');
  const binary = atob(padded);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }
  return bytes.buffer;
}
